### ISSUE TITLE
Во время паузы можно прыжками настакать ускорение и подлететь вверх

### ISSUE THREAD

**Issue by Voladsky** [Tatar3n/AgainstFate#103]
Если нажать на паузу, пока стоишь на поверхности, последовательно несколько раз нажать W, а потом отжать паузу, игрок подлетит вверх. Он взлетает сквозь потолок, но сквозь пол этажей выше не проходит. Я попробовал сделать этот баг на платформе в момент, когда змей говорит "не торопись", и вылетел за пределы карты.

В некоторых местах через потолок пролететь можно, где-то нельзя, не уверен, от чего это зависит

Видео с багом:
https://drive.google.com/file/d/14D1twreXMJDUb4VsUPwXBI4L8fI-ewkW/view?usp=sharing

**Comment by Tatar3n** [comment]
больше не подлетит ;)
